remote_theme: brunochanrio/material-jekyll-chanrio@2025.03.24
plugins:
- jekyll-remote-theme

title: DangoGuides en Español
author: Bruno-chanrio
logo: assets/DangoPlayerUni_Logo.png
mobilelogo: assets/DangoPlayerUni_Icon.png




baseurl: "/dangoguides_spanish"
color: "#FF7FAC"
accentColor: pink
themeColor: pink
fixedNav: 'true' # true or false
developedby: true

github_user: brunochanrio

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
