remote_theme: brunochanrio/material-jekyll-chanrio@2025.03.24
plugins:
- jekyll-remote-theme

title: DangoGuides en Español
author: Bruno-chanrio
logo: DangoPlayerUni_Logo.png



baseurl: "/dangoguides_spanish"
color: "#1DE9B6"
accentColor: teal
themeColor: purple
fixedNav: 'true' # true or false
developedby: true

github: brunochanrio

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
